version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - PREMIUMY_API=${PREMIUMY_API}
      - IPRN_API=${IPRN_API}
    restart: unless-stopped